=== miklesz/Courses/(Advanced) Multimedia Information Processing and Communications/05 Multimedia Content Storage and Description/metadata/BiM_impl/navigation_path/examples/fdis/video/examples.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="urn:mpeg:mpeg7:schema:2001"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:mpeg7="urn:mpeg:mpeg7:schema:2001"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified">

   <!--
      Include MPEG-7 schema
      <include schemaLocation="../schemaVer4/Mpeg7Ver4.xsd"/>
   -->
   <include schemaLocation="../Mpeg7Ver4.xsd"/>

   <!--
      Test schema for MdsExample
   -->
   <element name="MdsExampleTest">
      <complexType>
         <sequence maxOccurs="unbounded">
            <choice>
               <!-- 5.1 -->
               <element name="GridLayout" type="mpeg7:GridLayoutType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 5.2.2 -->
               <element name="RegularVisualTimeSeries" type="mpeg7:RegularVisualTimeSeriesType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 5.2.3 -->
               <element name="IrregularVisualTimeSeries" type="mpeg7:IrregularVisualTimeSeriesType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 5.3 -->
               <element name="MultipleView" type="mpeg7:MultipleViewType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 5.4 -->
               <element name="Spatial2DCoordinateSystem" type="mpeg7:Spatial2DCoordinateSystemType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 6.1 -->
               <element name="ColorSpace" type="mpeg7:ColorSpaceType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 6.2            -->
               <element name="ColorQuantization" type="mpeg7:ColorQuantizationType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 6.3            -->
               <element name="DominantColor" type="mpeg7:DominantColorType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 6.4            -->
               <element name="ScalableColor" type="mpeg7:ScalableColorType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 6.5            -->
               <element name="ColorLayout" type="mpeg7:ColorLayoutType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 6.6            -->
               <element name="ColorStructure" type="mpeg7:ColorStructureType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 6.7            -->
               <element name="GoFGoPColor" type="mpeg7:GoFGoPColorType" minOccurs="0" maxOccurs="unbounded"/>
               <!-- 7.1            -->
               <element name="HomogeneousTexture" type="mpeg7:HomogeneousTextureType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 7.2            -->
               <element name="TextureBrowsing" type="mpeg7:TextureBrowsingType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 7.3            -->
               <element name="EdgeHistogram" type="mpeg7:EdgeHistogramType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 8.1            -->
               <element name="RegionShape" type="mpeg7:RegionShapeType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 8.2            -->
               <element name="ContourShape" type="mpeg7:ContourShapeType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 8.3            -->
               <element name="Shape3D" type="mpeg7:Shape3DType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 9.1            -->
               <element name="CameraMotion" type="mpeg7:CameraMotionType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 9.2            -->
               <element name="MotionTrajectory" type="mpeg7:MotionTrajectoryType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 9.3            -->
               <element name="ParametricMotion" type="mpeg7:ParametricMotionType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 9.4            -->
               <element name="MotionActivity" type="mpeg7:MotionActivityType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 10.1            -->
               <element name="RegionLocator" type="mpeg7:RegionLocatorType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 10.2            -->
               <element name="SpatioTemporalLocator" type="mpeg7:SpatioTemporalLocatorType" minOcuurs="0" maxOccurs="unbounded"/>
               <!-- 11.1.            -->
               <element name="FaceRecognition" type="mpeg7:FaceRecognitionType" minOccurs="0" maxOccurs="unbounded"/>
               <!--             -->
               <element name="MediaTime" type="mpeg7:MediaTimeType" minOccurs="0" maxOccurs="unbounded"/>
            </choice>
         </sequence>
      </complexType>
   </element>
</schema>

=== miklesz/Courses/(Advanced) Multimedia Information Processing and Communications/05 Multimedia Content Storage and Description/metadata/BiM_impl/examples/3/video/ColorSpace.xml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<MdsExampleTest xmlns="urn:mpeg:mpeg7:schema:2001"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:mpeg7="urn:mpeg:mpeg7:schema:2001"
                xsi:schemaLocation="urn:mpeg:mpeg7:schema:2001 .\examples.xsd">

   <ColorSpace type="RGB"/>

   <ColorSpace type="YCbCr" colorReferenceFlag="true"/>

   <ColorSpace type="HSV"/>

   <ColorSpace type="HMMD" colorReferenceFlag="true"/>

   <ColorSpace type="LinearMatrix" colorReferenceFlag="true">
      <ColorTransMat>1 1 1 1 1 1 1 1 1</ColorTransMat>
   </ColorSpace>

   <ColorSpace type="Monochrome" colorReferenceFlag="true"/>


</MdsExampleTest>
